language: groovy
install: ./gradlew assemble -x javadoc javadocJar signArchive
script: ./gradlew check 
jdk:
  - oraclejdk7
  - oraclejdk8
git:
  submodules: false
env:
   global:
   - _JAVA_OPTIONS='-Xverify:none'
